default:
  config_name: public

  public:
    rspm_url: "https://packagemanager.rstudio.com/cran"
    environment:
      RENV_CONFIG_SANDBOX_ENABLED: TRUE
    renv_settings: 
      use.cache: TRUE
    date: NULL
    pkgs: NULL
    pkg_deps_ok: TRUE
    startup:
      pre: NULL
      post: NULL
